import { TeamDetail, TeamData } from "./types";

// 가나다순 (영문 팀명 우선)
export const TEAM_DETAILS: TeamDetail[] = [
  {
    id: "kia",
    order: 1,
    name: "KIA 타이거즈",
    stadium: "광주 기아 챔피언스 필드",
    color: "bg-kia",
    rank: 9,
    games: 140,
    wins: 56,
    losses: 74,
    draws: 10,
    winRate: 0.412,
    streak: "9승",
    players: [
      { id: "7", jerseyNumber: 7, name: "나성범", position: "외야수", average: ".301", details: "21HR 78RBI" },
      { id: "53", jerseyNumber: 53, name: "김도영", position: "내야수", average: ".312", details: "18HR 65RBI" },
      { id: "34", jerseyNumber: 34, name: "최형우", position: "지명타자", average: ".289", details: "15HR 70RBI" },
    ],
    coaches: [
      { id: "71", jerseyNumber: 71, name: "이범호", position: "감독", average: "", details: "" },
      { id: "72", jerseyNumber: 72, name: "김종국", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".268", rank: "8위" },
      { label: "홈런", value: "134", rank: "9위" },
      { label: "타점", value: "598", rank: "9위" },
      { label: "도루", value: "72", rank: "7위" },
      { label: "출루율", value: ".322", rank: "9위" },
      { label: "장타율", value: ".398", rank: "9위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "4.52", rank: "9위" },
      { label: "탈삼진", value: "985", rank: "9위" },
      { label: "이닝", value: "1189", rank: "9위" },
      { label: "WHIP", value: "1.42", rank: "9위" },
      { label: "세이브", value: "28", rank: "9위" },
      { label: "홀드", value: "45", rank: "9위" },
    ],
  },
  {
    id: "kt",
    order: 2,
    name: "KT 위즈",
    stadium: "수원 KT 위즈 파크",
    color: "bg-kt",
    rank: 4,
    games: 140,
    wins: 71,
    losses: 59,
    draws: 10,
    winRate: 0.513,
    streak: "4패",
    players: [
      { id: "47", jerseyNumber: 47, name: "강백호", position: "내야수", average: ".318", details: "29HR 91RBI" },
      { id: "10", jerseyNumber: 10, name: "황재균", position: "내야수", average: ".281", details: "17HR 62RBI" },
      { id: "21", jerseyNumber: 21, name: "배제성", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "77", jerseyNumber: 77, name: "이강철", position: "감독", average: "", details: "" },
      { id: "78", jerseyNumber: 78, name: "이진영", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".281", rank: "4위" },
      { label: "홈런", value: "158", rank: "3위" },
      { label: "타점", value: "645", rank: "5위" },
      { label: "도루", value: "88", rank: "4위" },
      { label: "출루율", value: ".341", rank: "5위" },
      { label: "장타율", value: ".421", rank: "4위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "3.98", rank: "4위" },
      { label: "탈삼진", value: "1098", rank: "4위" },
      { label: "이닝", value: "1245", rank: "4위" },
      { label: "WHIP", value: "1.31", rank: "4위" },
      { label: "세이브", value: "40", rank: "4위" },
      { label: "홀드", value: "65", rank: "4위" },
    ],
  },
  {
    id: "lg",
    order: 3,
    name: "LG 트윈스",
    stadium: "잠실 야구장",
    color: "bg-Lg",
    rank: 2,
    games: 140,
    wins: 77,
    losses: 53,
    draws: 10,
    winRate: 0.552,
    streak: "2패",
    players: [
      { id: "1", jerseyNumber: 1, name: "오지환", position: "내야수", average: ".291", details: "14HR 68RBI" },
      { id: "30", jerseyNumber: 30, name: "박해민", position: "외야수", average: ".303", details: "8HR 45RBI" },
      { id: "99", jerseyNumber: 99, name: "임찬규", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "75", jerseyNumber: 75, name: "염경엽", position: "감독", average: "", details: "" },
      { id: "76", jerseyNumber: 76, name: "차명석", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".289", rank: "2위" },
      { label: "홈런", value: "162", rank: "2위" },
      { label: "타점", value: "672", rank: "2위" },
      { label: "도루", value: "102", rank: "2위" },
      { label: "출루율", value: ".352", rank: "2위" },
      { label: "장타율", value: ".435", rank: "2위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "3.72", rank: "2위" },
      { label: "탈삼진", value: "1187", rank: "2위" },
      { label: "이닝", value: "1268", rank: "2위" },
      { label: "WHIP", value: "1.22", rank: "2위" },
      { label: "세이브", value: "48", rank: "2위" },
      { label: "홀드", value: "75", rank: "2위" },
    ],
  },
  {
    id: "nc",
    order: 4,
    name: "NC 다이노스",
    stadium: "창원 NC 파크",
    color: "bg-nc",
    rank: 6,
    games: 140,
    wins: 65,
    losses: 65,
    draws: 10,
    winRate: 0.473,
    streak: "6패",
    players: [
      { id: "22", jerseyNumber: 22, name: "손아섭", position: "외야수", average: ".295", details: "16HR 72RBI" },
      { id: "40", jerseyNumber: 40, name: "박민우", position: "내야수", average: ".278", details: "6HR 48RBI" },
      { id: "11", jerseyNumber: 11, name: "루친스키", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "80", jerseyNumber: 80, name: "강인권", position: "감독", average: "", details: "" },
      { id: "81", jerseyNumber: 81, name: "이종욱", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".274", rank: "6위" },
      { label: "홈런", value: "142", rank: "7위" },
      { label: "타점", value: "621", rank: "7위" },
      { label: "도루", value: "80", rank: "6위" },
      { label: "출루율", value: ".333", rank: "6위" },
      { label: "장타율", value: ".411", rank: "6위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "4.11", rank: "6위" },
      { label: "탈삼진", value: "1045", rank: "6위" },
      { label: "이닝", value: "1220", rank: "6위" },
      { label: "WHIP", value: "1.36", rank: "6위" },
      { label: "세이브", value: "34", rank: "6위" },
      { label: "홀드", value: "58", rank: "6위" },
    ],
  },
  {
    id: "ssg",
    order: 5,
    name: "SSG 랜더스",
    stadium: "인천 SSG 랜더스 필드",
    color: "bg-ssg",
    rank: 5,
    games: 140,
    wins: 68,
    losses: 62,
    draws: 10,
    winRate: 0.493,
    streak: "5승",
    players: [
      { id: "32", jerseyNumber: 32, name: "최정", position: "내야수", average: ".276", details: "31HR 88RBI" },
      { id: "9", jerseyNumber: 9, name: "추신수", position: "외야수", average: ".282", details: "12HR 55RBI" },
      { id: "58", jerseyNumber: 58, name: "김광현", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "83", jerseyNumber: 83, name: "이숭용", position: "감독", average: "", details: "" },
      { id: "84", jerseyNumber: 84, name: "이정훈", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".278", rank: "5위" },
      { label: "홈런", value: "151", rank: "5위" },
      { label: "타점", value: "634", rank: "6위" },
      { label: "도루", value: "85", rank: "5위" },
      { label: "출루율", value: ".338", rank: "5위" },
      { label: "장타율", value: ".418", rank: "5위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "4.02", rank: "5위" },
      { label: "탈삼진", value: "1072", rank: "5위" },
      { label: "이닝", value: "1232", rank: "5위" },
      { label: "WHIP", value: "1.33", rank: "5위" },
      { label: "세이브", value: "37", rank: "5위" },
      { label: "홀드", value: "62", rank: "5위" },
    ],
  },
  {
    id: "doosan",
    order: 6,
    name: "두산 베어스",
    stadium: "잠실 야구장",
    color: "bg-doosan",
    rank: 1,
    games: 140,
    wins: 80,
    losses: 50,
    draws: 10,
    winRate: 0.571,
    streak: "1승",
    players: [
      { id: "5", jerseyNumber: 5, name: "김현수", position: "외야수", average: ".315", details: "28HR 95RBI" },
      { id: "7", jerseyNumber: 7, name: "박건우", position: "외야수", average: ".298", details: "15HR 68RBI" },
      { id: "25", jerseyNumber: 25, name: "양의지", position: "포수", average: ".276", details: "18HR 71RBI" },
      { id: "37", jerseyNumber: 37, name: "이민호", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "71", jerseyNumber: 71, name: "이승엽", position: "감독", average: "", details: "" },
      { id: "72", jerseyNumber: 72, name: "홍성흔", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".295", rank: "1위" },
      { label: "홈런", value: "178", rank: "1위" },
      { label: "타점", value: "712", rank: "1위" },
      { label: "도루", value: "115", rank: "1위" },
      { label: "출루율", value: ".368", rank: "1위" },
      { label: "장타율", value: ".458", rank: "1위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "3.51", rank: "1위" },
      { label: "탈삼진", value: "1298", rank: "1위" },
      { label: "이닝", value: "1302", rank: "1위" },
      { label: "WHIP", value: "1.18", rank: "1위" },
      { label: "세이브", value: "55", rank: "1위" },
      { label: "홀드", value: "88", rank: "1위" },
    ],
  },
  {
    id: "lotte",
    order: 7,
    name: "롯데 자이언츠",
    stadium: "사직 야구장",
    color: "bg-lotte",
    rank: 8,
    games: 140,
    wins: 59,
    losses: 71,
    draws: 10,
    winRate: 0.432,
    streak: "8패",
    players: [
      { id: "23", jerseyNumber: 23, name: "전준우", position: "외야수", average: ".287", details: "18HR 74RBI" },
      { id: "1", jerseyNumber: 1, name: "안치홍", position: "내야수", average: ".271", details: "11HR 55RBI" },
      { id: "45", jerseyNumber: 45, name: "댄 스트레일리", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "78", jerseyNumber: 78, name: "김태형", position: "감독", average: "", details: "" },
      { id: "79", jerseyNumber: 79, name: "박정태", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".271", rank: "8위" },
      { label: "홈런", value: "138", rank: "8위" },
      { label: "타점", value: "609", rank: "8위" },
      { label: "도루", value: "76", rank: "8위" },
      { label: "출루율", value: ".327", rank: "8위" },
      { label: "장타율", value: ".404", rank: "8위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "4.38", rank: "8위" },
      { label: "탈삼진", value: "1010", rank: "8위" },
      { label: "이닝", value: "1198", rank: "8위" },
      { label: "WHIP", value: "1.40", rank: "8위" },
      { label: "세이브", value: "30", rank: "8위" },
      { label: "홀드", value: "50", rank: "8위" },
    ],
  },
  {
    id: "samsung",
    order: 8,
    name: "삼성 라이온즈",
    stadium: "대구 삼성 라이온즈 파크",
    color: "bg-samsung",
    rank: 7,
    games: 140,
    wins: 62,
    losses: 68,
    draws: 10,
    winRate: 0.453,
    streak: "7승",
    players: [
      { id: "24", jerseyNumber: 24, name: "오지환", position: "내야수", average: ".287", details: "22HR 82RBI" },
      { id: "13", jerseyNumber: 13, name: "구자욱", position: "외야수", average: ".305", details: "20HR 76RBI" },
      { id: "37", jerseyNumber: 37, name: "이민호", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "74", jerseyNumber: 74, name: "박진만", position: "감독", average: "", details: "" },
      { id: "75", jerseyNumber: 75, name: "이병규", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".275", rank: "7위" },
      { label: "홈런", value: "148", rank: "6위" },
      { label: "타점", value: "625", rank: "7위" },
      { label: "도루", value: "83", rank: "6위" },
      { label: "출루율", value: ".330", rank: "7위" },
      { label: "장타율", value: ".415", rank: "7위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "3.85", rank: "4위" },
      { label: "탈삼진", value: "1245", rank: "2위" },
      { label: "이닝", value: "1280", rank: "5위" },
      { label: "WHIP", value: "1.28", rank: "3위" },
      { label: "세이브", value: "45", rank: "3위" },
      { label: "홀드", value: "78", rank: "2위" },
    ],
  },
  {
    id: "kiwoom",
    order: 9,
    name: "키움 히어로즈",
    stadium: "고척 스카이돔",
    color: "bg-kiwoom",
    rank: 3,
    games: 140,
    wins: 74,
    losses: 56,
    draws: 10,
    winRate: 0.532,
    streak: "3승",
    players: [
      { id: "51", jerseyNumber: 51, name: "이정후", position: "외야수", average: ".340", details: "23HR 98RBI" },
      { id: "1", jerseyNumber: 1, name: "김혜성", position: "내야수", average: ".308", details: "10HR 58RBI" },
      { id: "22", jerseyNumber: 22, name: "안우진", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "86", jerseyNumber: 86, name: "홍원기", position: "감독", average: "", details: "" },
      { id: "87", jerseyNumber: 87, name: "장정석", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".285", rank: "3위" },
      { label: "홈런", value: "155", rank: "4위" },
      { label: "타점", value: "658", rank: "3위" },
      { label: "도루", value: "96", rank: "3위" },
      { label: "출루율", value: ".348", rank: "3위" },
      { label: "장타율", value: ".428", rank: "3위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "3.78", rank: "3위" },
      { label: "탈삼진", value: "1155", rank: "3위" },
      { label: "이닝", value: "1258", rank: "3위" },
      { label: "WHIP", value: "1.25", rank: "3위" },
      { label: "세이브", value: "44", rank: "3위" },
      { label: "홀드", value: "70", rank: "3위" },
    ],
  },
  {
    id: "hanwha",
    order: 10,
    name: "한화 이글스",
    stadium: "한화생명 이글스 파크",
    color: "bg-hanwha",
    rank: 10,
    games: 140,
    wins: 53,
    losses: 77,
    draws: 10,
    winRate: 0.391,
    streak: "10패",
    players: [
      { id: "10", jerseyNumber: 10, name: "노시환", position: "내야수", average: ".262", details: "35HR 102RBI" },
      { id: "31", jerseyNumber: 31, name: "채은성", position: "외야수", average: ".274", details: "14HR 60RBI" },
      { id: "44", jerseyNumber: 44, name: "류현진", position: "투수", average: "", details: "" },
    ],
    coaches: [
      { id: "89", jerseyNumber: 89, name: "김경문", position: "감독", average: "", details: "" },
      { id: "90", jerseyNumber: 90, name: "한용덕", position: "수석코치", average: "", details: "" },
    ],
    battingStats: [
      { label: "타율", value: ".262", rank: "10위" },
      { label: "홈런", value: "128", rank: "10위" },
      { label: "타점", value: "581", rank: "10위" },
      { label: "도루", value: "65", rank: "10위" },
      { label: "출루율", value: ".315", rank: "10위" },
      { label: "장타율", value: ".388", rank: "10위" },
    ],
    pitchingStats: [
      { label: "평균자책점", value: "4.68", rank: "10위" },
      { label: "탈삼진", value: "955", rank: "10위" },
      { label: "이닝", value: "1175", rank: "10위" },
      { label: "WHIP", value: "1.48", rank: "10위" },
      { label: "세이브", value: "24", rank: "10위" },
      { label: "홀드", value: "40", rank: "10위" },
    ],
  },
];

export const STANDINGS: TeamData[] = TEAM_DETAILS.map((t) => ({
  id: t.id,
  rank: t.rank,
  team: t.name,
  games: t.games,
  wins: t.wins,
  losses: t.losses,
  draws: t.draws,
  winRate: t.winRate,
  streak: t.streak,
})).sort((a, b) => (a.rank as number) - (b.rank as number));

export const getTeamById = (id: string): TeamDetail | undefined =>
  TEAM_DETAILS.find((t) => t.id === id);
