import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/assets/iconify-icons/generated-icons.css";
import QueryProvider from "@/providers/QueryProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import MainHeader from "@/components/ui/MainHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <QueryProvider>
          <ReduxProvider>
            <main className="mx-auto min-h-screen p-4 bg-[#fcfcfc] border border-gray-200">
            <MainHeader />
              {children}
            </main>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
